from os import getenv

DB_NAME = getenv("DB_NAME")
DB_HOST = getenv("DB_HOST")
DB_USER = getenv("DB_USER")
DB_PASSWORD = getenv("DB_PASSWORD")
DB_PORT = getenv("DB_PORT")
SUPABASE_URL = getenv("SUPABASE_URL")
SUPABASE_KEY = getenv("SUPABASE_KEY")
SUPABASE_LATEST_KEY = getenv("SUPABASE_LATEST_KEY", "latest.pgdump")
SUPABASE_LATEST_BUCKET = getenv("SUPABASE_LATEST_BUCKET")
SUPABASE_HISTORY_BUCKET = getenv("SUPABASE_HISTORY_BUCKET")
BACKUP_DIR = "/tmp"
MAX_BACKUP_QTY = int(getenv("MAX_BACKUP_QTY", 10))
