name: Build, Push and Deploy

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: |
            aptechnology/balneabilidade_tools:latest
            aptechnology/balneabilidade_tools:${{ github.event.release.tag_name }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run  
        uses: google-github-actions/deploy-cloudrun@v2  
        with:  
          image: docker.io/aptechnology/balneabilidade_tools:latest  
          service: balneabilidade-tools
          revision_traffic: 'LATEST=100'
          region: ${{ vars.GCP_REGION }}
          env_vars: |-            
            DB_PORT=${{ vars.DB_PORT }}
            SUPABASE_LATEST_KEY=${{ vars.SUPABASE_LATEST_KEY }}
            SUPABASE_LATEST_BUCKET=${{ vars.SUPABASE_LATEST_BUCKET }}
            SUPABASE_HISTORY_BUCKET=${{ vars.SUPABASE_HISTORY_BUCKET }}
            MAX_BACKUP_QTY=${{ vars.MAX_BACKUP_QTY }}      
            API_KEYS=${{ secrets.API_KEYS }}
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

      - name: Remove older revisions
        run: |
          gcloud run revisions list \
            --region ${{ vars.GCP_REGION }} \
            --service balneabilidade-tools \
            --format="value(REVISION)" \
            | tail -n +6 \
            | xargs -I {} \
            gcloud run revisions delete {} \
            --region ${{ vars.GCP_REGION }} \
            --quiet
