name: Build, Push and Deploy

on:
  release:
    types: [published]

env:
  IMAGE_NAME: aptechnology/balneabilidade_tools

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_NAME }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          sbom: true
          provenance: mode=max
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 363.0.0'
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Deploy to Cloud Run  
        uses: google-github-actions/deploy-cloudrun@v2  
        with:  
          image: docker.io/${{ env.IMAGE_NAME }}:latest  
          service: balneabilidade-tools
          revision_traffic: 'LATEST=100'
          region: ${{ vars.GCP_REGION }}
          env_vars: |-            
            DB_PORT=${{ vars.DB_PORT }}
            SUPABASE_LATEST_KEY=${{ vars.SUPABASE_LATEST_KEY }}
            SUPABASE_LATEST_BUCKET=${{ vars.SUPABASE_LATEST_BUCKET }}
            SUPABASE_HISTORY_BUCKET=${{ vars.SUPABASE_HISTORY_BUCKET }}
            MAX_BACKUP_QTY=${{ vars.MAX_BACKUP_QTY }}      
            DB_HOST=${{ secrets.DB_HOST }}
            DB_NAME=${{ secrets.DB_NAME }}
            DB_USER=${{ secrets.DB_USER }}
            DB_PASSWORD=${{ secrets.DB_PASSWORD }}
            SUPABASE_URL=${{ secrets.SUPABASE_URL }}
            SUPABASE_KEY=${{ secrets.SUPABASE_KEY }}

      - name: Delete old revisions
        run: |
          revisions=$(gcloud run revisions list \
            --service balneabilidade-tools \
            --region ${{ vars.GCP_REGION }} \
            --format="value(metadata.name)" \
            --sort-by=~createTime)

          revisions_to_delete=$(echo "$revisions" | tail -n +3)

          for revision in $revisions_to_delete; do
            echo "Deleting revision: $revision"
            gcloud run revisions delete $revision \
              --region ${{ vars.GCP_REGION }} \
              --quiet
          done
